[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = [] }
keyboard-types = "0.8.0"
ui = { workspace = true }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server"]
